In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
data = pd.read_csv('seller_prd_customer.csv')
data.head()

,Unnamed: 0,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,...,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/17 10:56,10/2/17 11:07,10/4/17 19:55,10/10/17 21:25,10/18/17 0:00,1,...,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,8/15/17 18:29,8/15/17 20:05,8/17/17 15:28,8/18/17 14:44,8/28/17 0:00,1,...,4.0,500.0,19.0,8.0,13.0,housewares,3a51803cc0d012c3b5dc8b7528cb05f7,3366,sao paulo,SP
2,2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,8/2/17 18:24,8/2/17 18:43,8/4/17 17:35,8/7/17 18:30,8/15/17 0:00,1,...,4.0,500.0,19.0,8.0,13.0,housewares,ef0996a1a279c26e7ecbd737be23d235,2290,sao paulo,SP
3,3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,delivered,10/23/17 23:26,10/25/17 2:14,10/27/17 16:48,11/7/17 18:04,11/13/17 0:00,1,...,4.0,500.0,19.0,8.0,13.0,housewares,e781fdcc107d13d865fc7698711cc572,88032,florianopolis,SC
4,4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,delivered,8/10/17 13:35,8/10/17 13:50,8/11/17 13:52,8/16/17 19:03,8/23/17 0:00,1,...,3.0,238.0,20.0,10.0,15.0,baby,02c9e0c05a817d4562ec0e8c90f29dba,8577,itaquaquecetuba,SP

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111023 entries, 0 to 111022
Data columns (total 30 columns):
Unnamed: 0                       111023 non-null int64
order_id                         111023 non-null object
customer_id                      111023 non-null object
order_status                     111023 non-null object
order_purchase_timestamp         111023 non-null object
order_approved_at                111009 non-null object
order_delivered_carrier_date     109868 non-null object
order_delivered_customer_date    108637 non-null object
order_estimated_delivery_date    111023 non-null object
order_item_id                    111023 non-null int64
product_id                       111023 non-null object
seller_id                        111023 non-null object
shipping_limit_date              111023 non-null object
price                            111023 non-null float64
freight_value                    111023 non-null float64
seller_zip_code_prefix           111023 non-null int64
seller_city                      111023 non-null object
seller_state                     111023 non-null object
product_name_lenght              111023 non-null float64
product_description_lenght       111023 non-null float64
product_photos_qty               111023 non-null float64
product_weight_g                 111022 non-null float64
product_length_cm                111022 non-null float64
product_height_cm                111022 non-null float64
product_width_cm                 111022 non-null float64
product_category_name_english    111023 non-null object
customer_unique_id               111023 non-null object
customer_zip_code_prefix         111023 non-null int64
customer_city                    111023 non-null object
customer_state                   111023 non-null object
dtypes: float64(9), int64(4), object(17)
memory usage: 25.4+ MB

In [46]:
#missing values count
print('missing values count')
print(111023-111009)
print(111023-109868)
print(111023-108637)

print('\nmissing values percentage')
#missing value percentage
print((111023-111009)/111023,'%')
print((111023-109868)/111023,'%')
print((111023-108637)/111023,'%')

missing values count
14
1155
2386

missing values percentage
0.0001260999972978572 %
0.01040324977707322 %
0.02149104239662052 %

In [7]:
data.describe()

,Unnamed: 0,order_item_id,price,freight_value,seller_zip_code_prefix,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_zip_code_prefix
count,111023.000000,111023.000000,111023.000000,111023.000000,111023.000000,111023.000000,111023.000000,111023.000000,111022.000000,111022.000000,111022.000000,111022.000000,111023.000000
mean,55511.000000,1.198229,120.755104,20.025548,24501.129180,48.774533,787.871549,2.209569,2099.897507,30.212210,16.624966,23.042172,35111.280104
std,32049.723805,0.706931,183.372746,15.841472,27646.694677,10.025953,652.169930,1.721428,3754.972723,16.190473,13.468184,11.717712,29854.973997
min,0.000000,1.000000,0.850000,0.000000,1001.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000,1003.000000
25%,27755.500000,1.000000,39.900000,13.080000,6429.000000,42.000000,348.000000,1.000000,300.000000,18.000000,8.000000,15.000000,11320.000000
50%,55511.000000,1.000000,74.990000,16.310000,13660.000000,52.000000,603.000000,1.000000,700.000000,25.000000,13.000000,20.000000,24340.000000
75%,83266.500000,1.000000,134.900000,21.180000,28470.000000,57.000000,987.000000,3.000000,1800.000000,38.000000,20.000000,30.000000,59020.000000
max,111022.000000,21.000000,6735.000000,409.680000,99730.000000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000,99980.000000

In [11]:
data = data.drop(columns = ['Unnamed: 0'])

In [12]:
data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,10/2/17 10:56,10/2/17 11:07,10/4/17 19:55,10/10/17 21:25,10/18/17 0:00,1,87285b34884572647811a353c7ac498a,...,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,8/15/17 18:29,8/15/17 20:05,8/17/17 15:28,8/18/17 14:44,8/28/17 0:00,1,87285b34884572647811a353c7ac498a,...,4.0,500.0,19.0,8.0,13.0,housewares,3a51803cc0d012c3b5dc8b7528cb05f7,3366,sao paulo,SP
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,8/2/17 18:24,8/2/17 18:43,8/4/17 17:35,8/7/17 18:30,8/15/17 0:00,1,87285b34884572647811a353c7ac498a,...,4.0,500.0,19.0,8.0,13.0,housewares,ef0996a1a279c26e7ecbd737be23d235,2290,sao paulo,SP
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,delivered,10/23/17 23:26,10/25/17 2:14,10/27/17 16:48,11/7/17 18:04,11/13/17 0:00,1,87285b34884572647811a353c7ac498a,...,4.0,500.0,19.0,8.0,13.0,housewares,e781fdcc107d13d865fc7698711cc572,88032,florianopolis,SC
4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,delivered,8/10/17 13:35,8/10/17 13:50,8/11/17 13:52,8/16/17 19:03,8/23/17 0:00,1,b00a32a0b42fd65efb58a5822009f629,...,3.0,238.0,20.0,10.0,15.0,baby,02c9e0c05a817d4562ec0e8c90f29dba,8577,itaquaquecetuba,SP

In [13]:
data.order_status.unique()

array(['delivered', 'processing', 'shipped', 'invoiced', 'canceled',
       'unavailable', 'approved'], dtype=object)

In [47]:
data['order_status'].value_counts()

delivered      108638
shipped          1158
canceled          526
invoiced          347
processing        344
unavailable         7
approved            3
Name: order_status, dtype: int64

In [14]:
len(data.order_id.unique())

97256

In [50]:
data['order_id'].value_counts().head(50)

8272b63d03f5f79c56e9e4120aec44ef    21
ab14fdcfbe524636d65ee38360e22ce8    20
1b15974a0141d54e36626dca3fdc731a    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
af822dacd6f5cff7376413c03a388bb7    12
3a213fcdfe7d98be74ea0dc05a8b31ae    12
637617b3ffe9e2f7a2411243829226d0    12
c05d6a79e55da72ca780ce90364abed9    12
2c2a19b5703863c908512d135aa6accc    12
7f2c22c54cbae55091a09a9653fd2b8a    11
5a3b1c29a49756e75f1ef513383c0c12    11
6c355e2913545fa6f72c40cbca57729e    11
71dab1155600756af6de79de92e712e3    11
9aec4e1ae90b23c7bf2d2b3bfafbd943    10
f60ce04ff8060152c83c7c97e246d6a8    10
ca3625898fbd48669d50701aba51cd5f    10
30bdf3d824d824610a49887486debcaf    10
a483ffe0ce133740ab12ebcba8a3ccf9    10
e8fa22c3673b1dd17ea315021b1f0f61    10
f80549a97eb203e1566e026ab66f045b    10
f368c3e5edb7b7db5296654ed37464b2     9
f5aa338a071dcf7d23d8e6b116bfcab5     9
c52c7fbe316b5b9d549e8a25206b8a1f     9
03caa2c082116e1d31e67e9ae3700499     8
848b0561d4bc26f57b288a5004f38683     8
9a2b443dc8e6673e4fc330b3ea033569     8
3cb5915708fd5b47246994508f858ffd     8
612d140e314dab491efb33ec8219c2ee     8
be382a9e1ed25128148b97d6bfdb21af     8
4affd1928d3900a415e9886a179d5124     8
04993613aee4046caf92ea17b316dcfb     8
487e6e67e10e5756f886f5994439c22f     7
1c11d0f4353b31ac3417fbfa5f0f2a8a     7
dc43adc8cf44306503fd3db002d5db5f     7
df13cbaf3230c62a4b582317936e8a39     7
895dce73de79888b14581541cf3a811b     7
7d8f5bfd5aff648220374a2df62e84d5     7
83f0c4c6b1a3c31214ca8266dc888258     7
1c437b4d4326d36b71e91dd7a7c2c4f6     7
cd51709c98c738351915f79c4318675e     7
62073ec6b54b8e6322037fc0f3591ad3     7
e37f11cae9985ca58f0b56f268720537     7
77df84f9195be22a4e9cb72ca9e8b4c2     7
dc3adcf742779e0c8eb5bd587ed4ec57     7
ad850e69fce9a512ada84086651a2e7d     7
7b598857cddf46a156640f69f70a6e6d     7
Name: order_id, dtype: int64

In [49]:
data['customer_id'].value_counts().head(50)

fc3d1daec319d62d49bfb5e1f83123e9    21
be1b70680b9f9694d8c70f41fa3dc92b    20
bd5d39761aa56689a265d95d8d32b8be    20
adb32467ecc74b53576d9d13a5a55891    15
10de381f8a8d23fff822753305f71cae    15
d5f2b3f597c7ccafbb5cac0bcc3d6024    14
a7693fba2ff9583c78751f2b66ecab9d    14
7d321bd4e8ba1caf74c4c1aabd9ae524    13
0d93f21f3e8543a9d0d8ece01561f5b2    12
91f92cfee46b79581b05aa974dd57ce5    12
9eb3d566e87289dcb0acf28e1407c839    12
daf15f1b940cc6a72ba558f093dc00dd    12
3b54b5978e9ace64a63f90d176ffb158    12
f4c13379ddd0ed4f4fc1c0b49c2c5e51    11
8c20d9bfbc96c5d39025d77a3ba83d7f    11
d95ca02ab50105ccce682bdf9ffdc3b4    11
be1c4e52bb71e0c54b11a26b8e8d59f2    11
1ff773612ab8934db89fd5afa8afe506    10
d6646ea91d8cd9fc7e6882a7068779d4    10
0d861a5e4dd6a9079d89e1330848f0ab    10
e2f063c52fa92b54f186c62b90699c10    10
78fc46047c4a639e81ff65f0396e02fe    10
4a60b2ce1ee8c7b828e4bbcca5b86b41    10
e7d6802668de6e74d0d6c56565bf2a24    10
da2060eb547f7d8c1753879cbf5c4a02     9
f4d64a735d1f90f13a057ca7f7b5ff87     9
88324c93ce11436ae046563bf0da285c     9
fd2ae8c714a773f85ef1b53fbebeda1f     8
0c792d32a3251b4f69dae8646dfbedbc     8
679f84ceb2ee4ca5bca0c3ea34647746     8
aeb3d464f6b83eecd79d6fd58d6208fb     8
f6af2b95b6be76fe88673d0a62a7db2f     8
1617b1357756262bfa56ab541c47bc16     8
4a38bf3ad3990d95c2c132f5bf530b95     8
20c93357daf05d1c3a092be59aea2c2b     8
046219c81738d6ee539ff6c04faa8575     7
3947a361301f2ff0f3223159a0f2701c     7
64ece241ae357ffb4989f7970a6f6adf     7
2f6d72365267ce6048d9bbc1a9bd977e     7
a828c4f615a8dd8518659d867b3012bd     7
a215ee5514ab937a137a58f476f4ec71     7
159132ab31eb3c8a1061ed18967f720b     7
9ae4bf2bb990fa503baa7e1feaf6f60e     7
9608550726f0135e52d3d72c08783afa     7
932289aae7b7195bc53d4c640ea071f4     7
a67a246af6ba598a14cc86df3c0354ee     7
30bb84b541c96af98ba7d90b9ebf35d0     7
1205480caca6c37f55954da838933b8a     7
6c7aa7f4eee619102606e20914da066a     7
ae546948bceb228b6f6a1980f9c28aca     7
Name: customer_id, dtype: int64

In [17]:
data.order_item_id.unique()

array([ 1,  2,  3,  4,  5,  6, 11,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21], dtype=int64)

In [27]:
data['order_item_id'].value_counts()

1     97229
2      9665
3      2256
4       954
5       453
6       254
7        58
8        35
9        28
10       25
11       17
12       13
13        8
14        7
15        5
20        3
16        3
17        3
18        3
19        3
21        1
Name: order_item_id, dtype: int64

In [22]:
product_cat = list(data.product_category_name_english.unique())

In [51]:
data.product_category_name_english.value_counts()

bed_bath_table                           11115
health_beauty                             9670
sports_leisure                            8641
furniture_decor                           8334
computers_accessories                     7827
housewares                                6964
watches_gifts                             5991
telephony                                 4545
garden_tools                              4347
auto                                      4235
toys                                      4117
cool_stuff                                3796
perfumery                                 3419
baby                                      3065
electronics                               2767
stationery                                2517
fashion_bags_accessories                  2031
pet_shop                                  1947
office_furniture                          1691
consoles_games                            1137
luggage_accessories                       1092
construction_tools_construction            929
home_appliances                            771
musical_instruments                        680
small_appliances                           679
home_construction                          604
books_general_interest                     553
food                                       510
furniture_living_room                      503
home_confort                               434
                                         ...
costruction_tools_garden                   238
home_appliances_2                          238
agro_industry_and_commerce                 212
art                                        209
computers                                  203
signaling_and_security                     199
construction_tools_safety                  194
christmas_supplies                         153
fashion_male_clothing                      132
fashion_underwear_beach                    131
furniture_bedroom                          109
costruction_tools_tools                    103
tablets_printing_image                      83
small_appliances_home_oven_and_coffee       76
cine_photo                                  72
dvds_blu_ray                                64
books_imported                              60
fashio_female_clothing                      48
party_supplies                              43
diapers_and_hygiene                         39
music                                       38
furniture_mattress_and_upholstery           38
flowers                                     33
fashion_sport                               30
home_comfort_2                              30
arts_and_craftmanship                       24
la_cuisine                                  14
cds_dvds_musicals                           14
fashion_childrens_clothes                    8
security_and_services                        2
Name: product_category_name_english, Length: 71, dtype: int64

In [26]:
data['customer_city'].value_counts()

sao paulo                   17512
rio de janeiro               7710
belo horizonte               3088
brasilia                     2360
curitiba                     1734
campinas                     1633
porto alegre                 1586
salvador                     1385
guarulhos                    1313
sao bernardo do campo        1039
niteroi                       966
santo andre                   879
osasco                        845
santos                        813
goiania                       795
sao jose dos campos           761
fortaleza                     719
sorocaba                      696
recife                        663
florianopolis                 648
jundiai                       642
ribeirao preto                578
nova iguacu                   494
belem                         477
contagem                      476
barueri                       472
juiz de fora                  466
mogi das cruzes               438
sao goncalo                   438
vitoria                       420
                            ...
sertao santana                  1
barao do triunfo                1
grupiara                        1
estiva                          1
piacatu                         1
duas barras                     1
purilandia                      1
acucena                         1
cedro                           1
aquidaba                        1
ingai                           1
mira estrela                    1
saboeiro                        1
sao jorge d'oeste               1
divinopolis do tocantins        1
nova america                    1
canto do buriti                 1
paraiso das aguas               1
serra azul                      1
sao desiderio                   1
rio grande do piaui             1
redencao da serra               1
sebastiao leal                  1
retirolandia                    1
caem                            1
marechal deodoro                1
cristopolis                     1
novais                          1
lagoa do carro                  1
jussiape                        1
Name: customer_city, Length: 4095, dtype: int64

In [28]:
data['customer_state'].value_counts()

SP    46782
RJ    14352
MG    12945
RS     6134
PR     5661
SC     4113
BA     3738
DF     2373
GO     2279
ES     2238
PE     1782
CE     1460
PA     1060
MT     1043
MA      813
MS      810
PB      592
PI      535
RN      523
AL      440
SE      383
TO      310
RO      272
AM      163
AC       90
AP       82
RR       50
Name: customer_state, dtype: int64

In [29]:
len(data.seller_id.unique())

3033

In [40]:
data['seller_id'].value_counts().head(200)

6560211a19b47992c3666cc44a7e94c0    2033
4a3ca9315b744ce9f8e9374361493884    1987
1f50f920176fa81dab994f9023523100    1931
cc419e0650a3c5ba77189a1882b7556a    1775
da8622b14eb17ae2831f4ac5b9dab84a    1551
955fee9216a65b617aa5c0531780ce60    1499
1025f0e2d44d7041d6cf58b6550e0bfa    1428
7c67e1448b00f6e969d365cea6b010ab    1364
ea8482cd71df3c1969d7b9473ff13abc    1203
7a67c85e85bb2ce8582c35f2203ad736    1171
4869f7a5dfa277a7dca6462dcf3b52b2    1156
3d871de0142ce09b7081e2b9d1733cb1    1147
8b321bb669392f5163d04c59e235e066    1018
cca3071e3e9bb7d12640c9fbe2301306     830
620c87c171fb2a6dd6e8bb4dec959fc6     798
a1043bafd471dff536d0c462352beb48     770
e9779976487b77c6d4ac45f75ec7afe9     750
f8db351d8c4c4c22c6835c19a46f01b0     721
d2374cbcbb3ca4ab1086534108cc3ab7     631
391fc6631aebcf3004804e51b40bcf1e     612
fa1c13f2614d7b5c4749cbc52fecda94     586
7d13fca15225358621be4086e1eb0964     578
128639473a139ac0f3e5f5ade55873a5     560
1835b56ce799e6a4dc4eddc053f04066     558
d91fb3b7d041e83b64a00a3edfb37e4f     536
1900267e848ceeba8fa32d80c1a5f5a8     529
85d9eb9ddc5d00ca9336a2219c97bb13     522
53e4c6e0f4312d4d2107a8c9cddf45cd     519
46dc3b2cc0980fb8ec44634e21d2718e     501
4e922959ae960d389249c378d1c939f5     437
                                    ...
6a8b085f816a1f75f92dbac6eb545f8f     135
00fc707aaaad2d31347cf883cd2dfe10     135
12b9676b00f60f3b700e83af21824c0e     135
59b22a78efb79a4797979612b885db36     133
42b729f859728f5079499127a9c2ef37     132
1127b7f2594683f2510f1c2c834a486b     132
cd68562d3f44870c08922d380acae552     132
01fdefa7697d26ad920e9e0346d4bd1b     131
b2479f944e1b90cf8a5de1bbfde284d6     131
aafe36600ce604f205b86b5084d3d767     131
609e1a9a6c2539919b8205cf7c4e6ff0     130
8e6d7754bc7e0f22c96d255ebda59eba     130
080102cd0a76b09e0dcf55fcacc60e05     130
17ca9b9e9b9ef8fdb529001b49ebb50f     129
febab0275244b9a49a623f0bd613ca2f     129
59fb871bf6f4522a87ba567b42dafecf     128
c33847515fa6305ce6feb1e818569f13     128
6c7d50c24b3ccd2fd83b44d8bb34e073     128
f80edd2c5aaa505cc4b0a3b219abf4b8     128
33a6f4b1e7cdc205511e76ba1b6e0186     126
289cdb325fb7e7f891c38608bf9e0962     126
e5a38146df062edaf55c38afa99e42dc     125
431af27f296bc6519d890aa5a05fdb11     125
c31eff8334d6b3047ed34bebd4d62c36     123
dd7ddc04e1b6c2c614352b383efe2d36     122
b1fc4f64df5a0e8b6913ab38803c57a9     121
3b15288545f8928d3e65a8f949a28291     121
f5a590cf36251cf1162ea35bef76fe84     119
dbb9b48c841a0e39e21f98e1a6b2ec3e     118
8c16d1f32a54d92897cc437244442e1b     118
Name: seller_id, Length: 200, dtype: int64

In [53]:
data['seller_id'].head()

0     3504c0cb71d7fa48d967e0e4c94d59d9
1     3504c0cb71d7fa48d967e0e4c94d59d9
2     3504c0cb71d7fa48d967e0e4c94d59d9
3     3504c0cb71d7fa48d967e0e4c94d59d9
4     3504c0cb71d7fa48d967e0e4c94d59d9
5     3504c0cb71d7fa48d967e0e4c94d59d9
6     3504c0cb71d7fa48d967e0e4c94d59d9
7     3504c0cb71d7fa48d967e0e4c94d59d9
8     3504c0cb71d7fa48d967e0e4c94d59d9
9     e26901d5ab434ce92fd9b5c256820a4e
10    e26901d5ab434ce92fd9b5c256820a4e
11    e26901d5ab434ce92fd9b5c256820a4e
12    e26901d5ab434ce92fd9b5c256820a4e
13    e26901d5ab434ce92fd9b5c256820a4e
14    e26901d5ab434ce92fd9b5c256820a4e
15    3504c0cb71d7fa48d967e0e4c94d59d9
16    3504c0cb71d7fa48d967e0e4c94d59d9
17    3504c0cb71d7fa48d967e0e4c94d59d9
18    3504c0cb71d7fa48d967e0e4c94d59d9
19    3504c0cb71d7fa48d967e0e4c94d59d9
20    3504c0cb71d7fa48d967e0e4c94d59d9
21    3504c0cb71d7fa48d967e0e4c94d59d9
22    3504c0cb71d7fa48d967e0e4c94d59d9
23    3504c0cb71d7fa48d967e0e4c94d59d9
24    3504c0cb71d7fa48d967e0e4c94d59d9
25    3504c0cb71d7fa48d967e0e4c94d59d9
26    3504c0cb71d7fa48d967e0e4c94d59d9
27    3504c0cb71d7fa48d967e0e4c94d59d9
28    3504c0cb71d7fa48d967e0e4c94d59d9
29    e26901d5ab434ce92fd9b5c256820a4e
Name: seller_id, dtype: object

In [60]:
data.groupby('seller_id')['product_category_name_english'].value_counts()

seller_id                         product_category_name_english
0015a82c2db000af6aaaf3ae2ecb0532  small_appliances                             3
001cca7ae9ae17fb1caed9dfb1094831  garden_tools                               212
                                  construction_tools_construction             27
001e6ad469a905060d959994f1b41e4f  sports_leisure                               1
002100f778ceb8431b7a1020ff7ab48f  furniture_decor                             55
004c9cd9d87a3c30c522c48c4fc07416  bed_bath_table                             158
00720abe85ba0859807595bbf045a33b  housewares                                  26
00ab3eff1b5192e5f1a63bcecfee11c8  health_beauty                                1
00d8b143d12632bad99c0ad66ad52825  fashion_bags_accessories                     1
00ee68308b45bc5e2660cd833c3f81cc  bed_bath_table                             150
                                  furniture_mattress_and_upholstery           22
00fc707aaaad2d31347cf883cd2dfe10  computers_accessories                      135
010543a62bd80aa422851e79a3bc7540  computers_accessories                        2
010da0602d7774602cd1b3f5fb7b709e  kitchen_dining_laundry_garden_furniture      5
011b0eaba87386a2ae96a7d32bb531d1  health_beauty                                2
01266d4c46afa519678d16a8b683d325  costruction_tools_tools                      3
013900e863eace745d3ec7614cab5b1a  fashion_shoes                               15
                                  baby                                        10
                                  stationery                                   1
014c0679dd340a0e338872e7ec85666a  kitchen_dining_laundry_garden_furniture     10
                                  signaling_and_security                       4
                                  garden_tools                                 1
014d9a685fd57276679edd00e07089e5  stationery                                   9
                                  cool_stuff                                   3
0176f73cc1195f367f7b32db1e5b3aa8  bed_bath_table                              39
01bcc9d254a0143f0ce9791b960b2a47  health_beauty                               11
01c97ebb5cdac52891c0ed1c37ba0012  computers_accessories                       12
01cf7e3d21494c41fb86034f2e714fa1  air_conditioning                            20
                                  housewares                                  19
                                  home_appliances_2                           13
                                                                            ...
ff82e8873fba613f2261a9acc896fd84  baby                                         3
                                  cool_stuff                                   1
ffa6adafb71b807dc13159e26431354c  cine_photo                                   5
                                  cool_stuff                                   5
                                  auto                                         3
                                  sports_leisure                               3
                                  garden_tools                                 2
ffad1e7127fb622cb64a900751590acd  furniture_decor                              9
                                  baby                                         6
ffc470761de7d0232558ba5e786e57b7  housewares                                  11
                                  construction_tools_construction              5
                                  garden_tools                                 5
                                  watches_gifts                                5
                                  signaling_and_security                       2
                                  auto                                         1
                                  furniture_decor                              1
                                  sports_leisure                               1
ffcfefa19b08742c5d315f2791395ee5  books_general_interest                       1
ffdd9f82b9a447f6f8d4b91554cc7dd3  housewares                                  17
                                  furniture_decor                              3
ffeee66ac5d5a62fe688b9d26f83f534  home_appliances                             14
fffd5413c0700ac820c7069d66d98c89  housewares                                  48
                                  furniture_decor                             12
                                  furniture_living_room                        1
ffff564a4f9085cd26170f4732393726  auto                                        10
                                  electronics                                  2
                                  food                                         2
                                  housewares                                   2
                                  construction_tools_construction              1
                                  market_place                                 1
Name: product_category_name_english, Length: 6352, dtype: int64

In [61]:
data.groupby('seller_id')['product_category_name_english'].value_counts().sort_values(ascending=False).head(20)

seller_id                         product_category_name_english
1f50f920176fa81dab994f9023523100  garden_tools                     1882
6560211a19b47992c3666cc44a7e94c0  watches_gifts                    1628
4a3ca9315b744ce9f8e9374361493884  bed_bath_table                   1572
1025f0e2d44d7041d6cf58b6550e0bfa  furniture_decor                  1292
da8622b14eb17ae2831f4ac5b9dab84a  bed_bath_table                   1277
7c67e1448b00f6e969d365cea6b010ab  office_furniture                 1233
ea8482cd71df3c1969d7b9473ff13abc  telephony                        1178
cc419e0650a3c5ba77189a1882b7556a  health_beauty                    1091
7a67c85e85bb2ce8582c35f2203ad736  cool_stuff                       1069
4869f7a5dfa277a7dca6462dcf3b52b2  watches_gifts                    1002
8b321bb669392f5163d04c59e235e066  electronics                       910
3d871de0142ce09b7081e2b9d1733cb1  stationery                        834
cc419e0650a3c5ba77189a1882b7556a  perfumery                         657
d2374cbcbb3ca4ab1086534108cc3ab7  bed_bath_table                    597
fa1c13f2614d7b5c4749cbc52fecda94  watches_gifts                     579
1835b56ce799e6a4dc4eddc053f04066  bed_bath_table                    553
cca3071e3e9bb7d12640c9fbe2301306  furniture_decor                   544
128639473a139ac0f3e5f5ade55873a5  electronics                       540
955fee9216a65b617aa5c0531780ce60  furniture_decor                   535
1900267e848ceeba8fa32d80c1a5f5a8  bed_bath_table                    519
Name: product_category_name_english, dtype: int64

In [63]:
data.groupby('product_category_name_english')

KeyError: 'Column not found: bed_bath_table'